#!/bin/bash

if [ $USER != "root" ]; then
	echo "need root privilege"
	exit 0
fi


HW_NAME=$1

if [ "$HW_NAME" = "" ]; then
	echo "usage: sudo ./install [HW_NAME]"
	exit 0
fi

H_HW_NAME="h_$HW_NAME"


cd HomeworkCodes/$HW_NAME/skeleton
mkdir tmp
cp ../../../HomeworkInspector/src/shm_makefile tmp/makefile
cp ../../../HomeworkInspector/src/shm_writer.cpp tmp
cp {data.hpp,hidden_data.hpp,input.txt,hidden_input.txt} tmp

cd tmp
make all > /dev/null
./shm_writer clean

mv hidden_data.hpp data.hpp
./shm_writer clean

cd ..
rm -rf tmp
cd ../../..

